### ISSUE TITLE
Code validation on upload not working correctly

### ISSUE THREAD

**Issue by swimberg** [HMSADMSYS/prompt#184]
It looks like something has changed since the last release with how the code validation happens when doing an upload.

If any segment of the code string comes back as invalid from the validation service, the invoice should still be created, but the default code for the customer should be used.  Currently on http://production.prompt.devshop.site, if a code segment is invalid, the upload is cancelled.  This is also true in our staging environment here at HMS.

On the HMS production site, if a bad code is in an upload, the invoice is still created, but the default code for the customer is used instead of the bad code.

I've attached screen shots of the upload result on the HMS production site (successful) and on the devshop site (unsuccessful), as well as the spreadsheet I was using to test.
[hms-idbp-invoice-MS-codetest.xlsx](https://github.com/HMSADMSYS/prompt/files/348264/hms-idbp-invoice-MS-codetest.xlsx)

![unsuccessfulupload](https://cloud.githubusercontent.com/assets/7936089/16593425/3b986872-42b3-11e6-86b3-b48d4100b434.jpg)
![successfulupload](https://cloud.githubusercontent.com/assets/7936089/16593424/3b94c636-42b3-11e6-8485-39bff95b5085.jpg)

**Comment by swimberg** [comment]
[hms-idbp-invoice-MS-codetest.xlsx](https://github.com/HMSADMSYS/prompt/files/348274/hms-idbp-invoice-MS-codetest.xlsx)

**Comment by swimberg** [comment]
Hi Jon,
When do you think you might have a chance to take a look at this?
Steve

**Comment by jonpugh** [comment]
@swimberg I believe the only time that the code is replaced with the default is when the code is left empty. I think it's safer to warn users of invalid codes in case they need to specify a custom one and made a typo. Just using the default might result in incorrect invoice, and the users would have to delete or fix...

It's worth considering implementing that if users can still edit the invoices on the website. They'll have to do it either on the website or the spreadsheet, and I guess the website is easier.

See this code for the logic that inserts the default code.
https://github.com/HMSADMSYS/prompt/blob/master/sites/all/modules/custom/hms_invoice/includes/upload.inc#L493

That error message "Value 0022 has been disabled" ... That is coming from the validator.

Can you check the "Account Code Validation URL" on your production website?  At http://production.prompt.devshop.site/admin/config/portal/settings it is set as apollo36.

If your production server is set to apollo 34, perhaps the database on apollo36 has changed? That message "Value 0022 has been disabled" gives the a feeling that the entity that is represented by 0022 is missing or disabled...

To test this out, you can alter the  "Account Code Validation URL" on  production, if you just fill in a new URL and hit the "test" button it will attempt validation without changing config.

Put the HMS code from the spreadsheet, i think you will get the error "Value 0022 has been disabled" when using apollo36 (testing server), but not on apollo34 (production)...

Can you confirm this? 

Thanks,
Jon

**Comment by jonpugh** [comment]
In order to debug further, I'd need to know what version your production server is running.

Can you login and run "git show" and copy the output here?

Thanks!

**Comment by swimberg** [comment]
Hi Jon,

Here is the output, but it just kept repeating over and over:


commit ff208f77d1a9a0462611da764e11f9a3f06b7bc0

Author: Jon Pugh <jon@thinkdrop.net>

Date:   Wed Apr 15 12:20:42 2015 -0400


    Checking for lab and requester on singularly uploaded


diff --git a/behat/features/invoiceNew.feature b/behat/features/invoiceNew.fea

index c8c3d0e..e3c05ed 100644

--- a/behat/features/invoiceNew.feature

+++ b/behat/features/invoiceNew.feature

@@ -50,6 +50,7 @@ Feature: Create an Invoice

     Then I should see "has been updated"

     And I should see "DNA Resource Core"



-      # It works on edit

+    And I should see "Test Lab"

+    And I should see "Test Requester"

     And I should see "2,000"

     And I should see "444"


Steve

**Comment by swimberg** [comment]
Hi Jon,

I know it sounds weird, but if the code is incorrect or blank on the upload, the default code should be inserted.  This puts the responsibility of providing a valid code on the customer, not the core.  This is how it works currently on our production site, so I’m not sure what has changed with the code on our staging site.

Apollo36 is the production GL server and apollo34 is test.  However, there is no test validation service, that I know of.  To test validation (and only validation, not the upload to the GL) we use apollo36.

The error message “Value 0022 has been disabled” is definitely coming from the validator.  These messages show to the customer when they edit the codes on the invoice, but are not necessary to show to the core when they upload their invoices.

Steve

**Comment by jonpugh** [comment]
Ok, so for the bulk uploader, if a code is invalid, we will insert the default.

**Comment by jonpugh** [comment]
Looks like it works now!

- I created a new release v1.1.0 that includes the "Banned Characters" setting.
- Created a new "release" environment to test out: http://release.prompt.devshop.site/ 
- I uploaded your attached spreadsheet, and it worked, adding a message about an invalid code but not failing form submission:

![screen shot 2016-07-25 at 3 34 15 pm](https://cloud.githubusercontent.com/assets/106420/17114560/750158f6-527d-11e6-9b13-9dce8b3427ce.png)
